---
- name: packes - proxy
  hosts: proxy
  become: true

  tasks:
  - name: install pkgs
    yum:
     name: 
      - httpd
      - wget
     state: absent

- name: packes - dev
  hosts: dev
  become: true

  tasks:
  - name: install pkgs - dev
    yum:
     name: "@Development tools"
     state: installed

